### PR TITLE
Add edge.svg for edge templates

### PR DESCRIPTION
**Pull request by thetutlage**
Edge is a Node.js templating engine. http://edge.adonisjs.com/

Really sorry, but I am not able to run `make` it complains `cp: dist/file-icons.ttf: No such file or directory`

If I manually drop a `file-icons.ttf` file inside the dist directory, it complains Missing `/fonts/file-icons.woff2`

### CODE REVIEW

**Comment by thetutlage** [comment]
Ohhh, went with the flow after seeing other PR's. My bad!. Thanks for being patient

**Comment by Alhadis** [comment]
Yeah, sorry. Currently not taking pull-requests anymore. Going through IcoMoon is fiddly and time-consuming for contributors, and I end up having to replace the icon with an optimised version anyway (which, again, involves regenerating the font with IcoMoon). Basically, it's faster for users to submit new icons as issue attachments, and certainly much easier for me to kick open Illustrator and check for any redundant geometry.

Eventually I'll develop a streamlined solution. I can't say when.

I should probably remove the rest of the readme for the time being, so as to confuse less people.

**Comment by thetutlage** [comment]
No issues and thanks for maintaining these icons 👍

**Comment by Alhadis** [comment]
@thetutlage Just letting you know it might be a while until the next `file-icons` release. If you really want to see the icon now, you can use your stylesheet and the font you generated:

~~~less
@font-face {
	font-family: file-icons;
	font-weight: normal;
	font-style: normal;
	src: url("file:///Users/YOURNAME/.atom/file-icons2.woff") format("woff");
}

.icon[data-name$=".FILE_SUFFIX"]:before{
	font-family: file-icons;
	content: "\ea78";
}
~~~

Which can be safely removed after the next package upgrade.

**Comment by thetutlage** [comment]
👍

**Pull request merged**
